# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image:
  name: gitlab-master.nvidia.com:5005/earth-2/fcn-mip:latest
  entrypoint: [/opt/entrypoint.sh, bash, -c]

sphinx:
  tags:
    - pages
  only:
    - main
  script:
    - make -C docs html
    - mv -r docs/_build/html public/
  artifacts:
    paths:
    - public/
